[project]
name = "portfolio-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "isa.bidou@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "docx2txt>=0.9",
    "gradio>=6.27.0",
    "langchain-chroma>=1.1.0",
    "langchain-core>=1.6.3",
    "langchain-huggingface>=1.2.2",
    "langchain-openai>=1.6.2",
    "langchain-text-splitters>=1.1.2",
    "pypdf>=6.18.1",
    "pysqlite3-binary>=0.5.4; sys_platform == 'linux' and platform_machine == 'x86_64'",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.0.1",
]

[project.scripts]
portfolio-rag = "portfolio_rag:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
